// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMT18C_Odv8Hsb_hVkuTvgM0OQ2WpCguc',
    appId: '1:375403365836:web:439c85272283762ba84969',
    messagingSenderId: '375403365836',
    projectId: 'suvidha-sathi-2972c',
    authDomain: 'suvidha-sathi-2972c.firebaseapp.com',
    storageBucket: 'suvidha-sathi-2972c.firebasestorage.app',
    measurementId: 'G-5KC7J10FJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHuAFebLSv8wWTWkBTwOeKcGAFVSgT3Dw',
    appId: '1:375403365836:android:73596603627c811fa84969',
    messagingSenderId: '375403365836',
    projectId: 'suvidha-sathi-2972c',
    storageBucket: 'suvidha-sathi-2972c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ7mgSDrratULt9abBQ5JWnBQWkVH9edY',
    appId: '1:375403365836:ios:7b945eb633772dafa84969',
    messagingSenderId: '375403365836',
    projectId: 'suvidha-sathi-2972c',
    storageBucket: 'suvidha-sathi-2972c.firebasestorage.app',
    iosClientId: '375403365836-0mkl9m6n31vghd97bdnfb0kpjc7qn4hi.apps.googleusercontent.com',
    iosBundleId: 'com.example.suvidhaSathi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ7mgSDrratULt9abBQ5JWnBQWkVH9edY',
    appId: '1:375403365836:ios:7b945eb633772dafa84969',
    messagingSenderId: '375403365836',
    projectId: 'suvidha-sathi-2972c',
    storageBucket: 'suvidha-sathi-2972c.firebasestorage.app',
    iosClientId: '375403365836-0mkl9m6n31vghd97bdnfb0kpjc7qn4hi.apps.googleusercontent.com',
    iosBundleId: 'com.example.suvidhaSathi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMT18C_Odv8Hsb_hVkuTvgM0OQ2WpCguc',
    appId: '1:375403365836:web:64c024aba85b8f84a84969',
    messagingSenderId: '375403365836',
    projectId: 'suvidha-sathi-2972c',
    authDomain: 'suvidha-sathi-2972c.firebaseapp.com',
    storageBucket: 'suvidha-sathi-2972c.firebasestorage.app',
    measurementId: 'G-X4EM3LPSQK',
  );

}